# Generated by Django 6.0.2 on 2026-02-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blynk_auth_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="iot_platform",
            field=models.CharField(
                choices=[
                    ("none", "None / Will add later"),
                    ("thingspeak", "ThingSpeak"),
                    ("blynk", "Blynk IoT"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
